import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent))", foreground: "hsl(var(--accent-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        vscode: {
          bg: "hsl(var(--vscode-bg))",
          sidebar: "hsl(var(--vscode-sidebar))",
          activity: "hsl(var(--vscode-activity))",
          tabActive: "hsl(var(--vscode-tab-active))",
          tabInactive: "hsl(var(--vscode-tab-inactive))",
          panel: "hsl(var(--vscode-panel))",
          statusBar: "hsl(var(--vscode-status-bar))",
          statusBarFg: "hsl(var(--vscode-status-bar-fg))",
          text: "hsl(var(--vscode-text))",
          textMuted: "hsl(var(--vscode-text-muted))",
          accent: "hsl(var(--vscode-accent))",
          selection: "hsl(var(--vscode-selection))",
          lineHighlight: "hsl(var(--vscode-line-highlight))",
          border: "hsl(var(--vscode-border))",
          hover: "hsl(var(--vscode-hover))",
          keyword: "hsl(var(--vscode-keyword))",
          string: "hsl(var(--vscode-string))",
          function: "hsl(var(--vscode-function))",
          comment: "hsl(var(--vscode-comment))",
          number: "hsl(var(--vscode-number))",
          type: "hsl(var(--vscode-type))",
          variable: "hsl(var(--vscode-variable))",
          iconActive: "hsl(var(--vscode-icon-active))",
          iconInactive: "hsl(var(--vscode-icon-inactive))",
        },
        status: {
          green: "hsl(var(--status-green))",
          amber: "hsl(var(--status-amber))",
          violet: "hsl(var(--status-violet))",
        },
      },
      fontFamily: {
        mono: ["'JetBrains Mono'", "Fira Code", "Consolas", "Monaco", "monospace"],
        sans: ["Inter", "Segoe UI", "system-ui", "sans-serif"],
        display: ["Inter", "Segoe UI", "system-ui", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "fade-in": { "0%": { opacity: "0", transform: "translateY(8px)" }, "100%": { opacity: "1", transform: "translateY(0)" } },
        "scale-in": { "0%": { opacity: "0", transform: "scale(0.96)" }, "100%": { opacity: "1", transform: "scale(1)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.4s ease-out both",
        "scale-in": "scale-in 0.3s ease-out both",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
